#!/usr/bin/env bash

FORCE_INSTALL_PRE=${FORCE_INSTALL_PRE:-false}
NODE_PREFIX=${NODE_PREFIX:-unknown}
NODE_NUM=${NODE_NUM:-1}
NODE_CPUS=${NODE_CPUS:-1}
NODE_MEM=${NODE_MEM:-2G}
PUB_KEY=${PUB_KEY:-$HOME/.ssh/id_rsa.pub}
PRI_KEY=${PRI_KEY:-$HOME/.ssh/id_rsa}